### ISSUE TITLE
(Existing Project & New Project) Permissions & Folders missing when Script is run without Users 

### ISSUE THREAD

**Issue by contech101** [tumcms/forge-bim360.project.setup.tool#4]
When i run the Script to add "Folders only" to an existing Project some Permissions are not added.
The current workaround is to execute the same script twice or 3 Times. 
I was working currently on a single Project with had 500 Lines of Folders and needed to run it 4 times to include settings
https://youtu.be/b0gGk7sy3Ls?list=PL_ph56WaRJ7IsN7nXa6K5NUO-nNJegiYd&t=789

**Comment by seb-esser** [comment]
@tumcms/bim360-project-setup-team will have a look soon.
